Algoritmo "divida impagavél da rainha"

Var

quantquad, quantgraos, casa : real


Inicio
quantquad <- 64
quantgraos <-1
casa <- 1
enquanto casa <= quantquad faca
         quantgraos := quantgraos *2
         casa := casa +1

fimenquanto
escreva("A quantidade de quadros do xadrez é: ", quantquad, " e a quantidade de grãos é: ", quantgraos, " a quantidade de casas calculada é :",casa)


Fimalgoritmo