Algoritmo "Media do Aluno"
// Descrição   : Aprovar ou Reprovar
// Autor(a)    : Albérico Ben-Hur Carneiro de Andrade
// Data atual  : 06/05/2021
Var

Media: real

Inicio
escreva ("Digite o valor da media do aluno ")
leia (Media)

se Media > 5 então
escreva ("Aluno aprovado!")
fimse
se Media = 5 então
escreva ("Aluno deve ir para recuperação")
fimse
se Media < 5 então
escreva ("Aluno reprovado")
fimse


Fimalgoritmo